name: FactionStats
version: 2.1.0
main: me.yourname.factionstats.FactionStats
api-version: 1.21

commands:
  fstats:
    description: Show your stats or top factions
    usage: /fstats [top|create|join]
