name: FactionStats
version: 1.1
main: com.thegoat.factionstats.FactionStats
api-version: 1.21
commands:
  fstats:
    description: Shows your faction statistics
    usage: /fstats
    permission: factionstats.use
permissions:
  factionstats.use:
    default: true
